// app/[locale]/layout.tsx
import { dir } from "i18next";
// import { i18nConfig } from "@/i18n.config";
import "../../../lib/i18nClient"; // This will initialize the client i18n setup
import type { Metadata } from "next";
import {
  Inter,
  Nunito,
  Poppins,
  Roboto,
  Source_Sans_3,
} from "next/font/google";
import "../globals.css";
import FirebaseWrapper from "@/components/FirebaseWrapper";
import AppSidebarLayout from "@/components/layout/sidebar/sidebarLayout";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});
const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-source-sans",
});

export const metadata: Metadata = {
  title: "Koloride | Admin",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <div
      lang={locale}
      dir={dir(locale)}
      className={`${inter.variable} ${nunito.variable} ${poppins.variable} ${roboto.variable} ${sourceSans3.variable}`}
    >
      <FirebaseWrapper>
        <ReactQueryProvider>
          <AppSidebarLayout>
            {children}
            <Toaster />
          </AppSidebarLayout>
        </ReactQueryProvider>
      </FirebaseWrapper>
    </div>
  );
}
